name: Android CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Lint
        run: ./gradlew lint -Dlint.baselines.continue=true

      - name: Upload Lint Report
        uses: actions/upload-artifact@v2
        with:
          name: lint-report
          path: app/build/reports/lint/lint-results.html

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: AndroidCICD.apk
          path: app/build/outputs/apk/debug/app-debug.apk